---
title: "R Notebook"
output: html_notebook
---

```{r}
DENV2_count <- coldv2 %>% remove_rownames %>% column_to_rownames(var="SymbolID")
View(DENV2_count) # colData for DENV2 set

#View(merge_GA_NoRowName)

#MGAdf <- as.data.frame(merge_GA)

MD2 <- as.data.frame(Metadata_2)

dds_2 <- DESeqDataSetFromMatrix(countData = round(coldvD2), colData = MD2, design= ~ batch + condition)

write.csv( as.data.frame(DENV2_count), file = "DENV2_count.csv")
countD2GA <- read_excel("/Users/runchie/Desktop/Ph.D./DEA_runchana/DENV2_count.xlsx", sheet = "DENV2_count")
coldvD2 <- countD2GA %>% remove_rownames %>% column_to_rownames(var="...1")
View(coldvD2)

dds_2$condition <- relevel(dds_2$condition, ref = "untreated")

dds_2 <- DESeq(dds_2)
resultsNames(dds_2)

resD2 <- results(dds_2, name="condition_treated_vs_untreated")
view(resD2)

resSigD2 <- subset(resD2, padj < 0.01)
resSigD2 # input for ggplot2
summary(resSigD2)

write.csv(resSigD2, "~/Desktop/resSigD2.csv")

mm <- org.Mm.eg.db
entrez <- AnnotationDbi::select(mm, 
                                keys = rownames(resSigD2),
                                columns = c("ENTREZID", "SYMBOL"),
                                keytype = "SYMBOL")
entrez <- distinct(entrez, SYMBOL, .keep_all = TRUE) #removes duplicate entries if there was multiple mapping
resSigD2$entrez <- entrez$ENTREZID

write.csv(resSigD2, "~/Desktop/resSigD2.csv", row.names = FALSE)

#resSigD2_noNA <- filter(resSigD2, entrez != "NA")
resSigD2_noNA <- resSigD2[complete.cases(resSigD2), ] #  with omitted NA
head(resSigD2_noNA)

resSigD2_GSEA <- as.data.frame(resSigD2_noNA)

write.csv(resSigD2_noNA, "~/Desktop/resSigD2_noNA.csv", row.names = FALSE)

geneList <- resSigD2_noNA$log2FoldChange     
names(geneList) = as.character(resSigD2_noNA$entrez)   
#gene <- dplyr::filter(resSigD2_noNA, abs(log2FoldChange) > 2)
sortedgeneList <- sort(geneList, decreasing = T)
sortedgeneList_df <- as.data.frame(sortedgeneList)

#write.csv(gene, "~/Desktop/D2_sig_genes.csv", row.names = FALSE)

#gene <- gene$entrez

ego <- enrichGO(gene          = gene,
                universe      = names(geneList),
                OrgDb         = org.Mm.eg.db,
                ont           = "ALL",        #BP, CC, or MF
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.05,
                qvalueCutoff  = 0.1,
                readable      = TRUE)
go_df <- as.data.frame(ego@result)

```

```{r}
#UPREG
UPREG_DENV2 <- read_excel("/Users/runchie/Desktop/Ph.D./DEA_runchana/upreg_DENV2.xlsx", sheet = "Sheet1")

UPREG_DENV2_noNA <- UPREG_DENV2[complete.cases(UPREG_DENV2 ), ] #  with omitted NA
head(UPREG_DENV2_noNA)
write.csv(UPREG_DENV2_noNA, "~/Desktop/UPREG_DENV2_noNA.csv", row.names = FALSE)

genelist_UPREG_DENV2 <- read_excel("/Users/runchie/Desktop/Ph.D./DEA_runchana/genelist_upreg_DENV2.xlsx", sheet = "Sheet1")

genelist_UPREG_DENV2 <- as.vector(genelist_UPREG_DENV2)



geneListUP <- UPREG_DENV2_noNA$log2FoldChange     
names(geneListUP) = as.character(UPREG_DENV2_noNA$entrez)   
#gene <- dplyr::filter(resSigD2_noNA, abs(log2FoldChange) > 2)
geneUP <- UPREG_DENV2_noNA$entrez

#write.csv(geneUP, "~/Desktop/geneUP.csv", row.names = FALSE)


egoUP <- enrichGO(gene          = geneUP,
                universe      = genelist_UPREG_DENV2,
                OrgDb         = org.Mm.eg.db,
                ont           = "CC",        #BP, CC, or MF
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.05,
                qvalueCutoff  = 0.1,
                readable      = TRUE)
go_dfUP <- as.data.frame(egoUP@result)
go_UP <- as.data.frame(egoUP)



UP_plot <- plot(barplot(egoUP, 
        x = "Count",
        color = "p.adjust",
        showCategory = 20))
png(filename="~/Desktop/Upreg_DENV2_barplot_CC.png", width=10, height=10, units="in", res=300)
print(UP_plot)
dev.off()

#go_dfUP <- distinct(go_dfUP, geneID, .keep_all = TRUE)
go_dfUP_20 <- go_dfUP[1:20,]

desUP <- go_dfUP_20$Description
desUP <- rev(desUP)
go_dfUP_20$Description <- factor(go_dfUP_20$Description, levels = go_dfUP_20$Description[order(-(go_dfUP_20$pvalue))])

egoplotUP <- ggplot(egoUP)

if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("enrichplot")
library(enrichplot)

#GO Figure Lung 
png(filename="~/Desktop/Upreg_DENV2_GP.png", width=8, height=6, units="in", res=300)
ggplot(go_dfUP_20, aes(Description, Count, fill=p.adjust)) + 
  geom_col() +
  coord_flip() +
  scale_x_discrete(labels = str_wrap(des, width = 60)) +
  #scale_fill_viridis() +
  ylab("Number Enriched") +
  xlab("GO Term") +
  theme(
    legend.position = "right",
    text = element_text(size = 10),
    axis.title.x = element_text(size = 10), 
    axis.title.y = element_text(size = 10))

#####################

#DOWNREG
DOWNREG_DENV2 <- read_excel("/Users/runchie/Desktop/Ph.D./DEA_runchana/downreg_DENV2.xlsx", sheet = "Sheet1")

genelist_DOWNREG_DENV2 <- read_excel("/Users/runchie/Desktop/Ph.D./DEA_runchana/genelist_downreg_DENV2.xlsx", sheet = "Sheet1")

DOWNREG_DENV2_noNA <- DOWNREG_DENV2[complete.cases(DOWNREG_DENV2 ), ] #  with omitted NA
View(DOWNREG_DENV2_noNA)
write.csv(DOWNREG_DENV2_noNA, "~/Desktop/DOWNREG_DENV2_noNA.csv", row.names = FALSE)

geneListDOWN <- DOWNREG_DENV2_noNA$log2FoldChange     
names(geneListDOWN) = as.character(DOWNREG_DENV2_noNA$entrez)   
#gene <- dplyr::filter(resSigD2_noNA, abs(log2FoldChange) > 2)
geneDOWN <- DOWNREG_DENV2_noNA$entrez

genelist_DOWNREG_DENV2 <- read_excel("/Users/runchie/Desktop/Ph.D./DEA_runchana/genelist_downreg_DENV2.xlsx", sheet = "Sheet1")

genelist_DOWNREG_DENV2 <- as.vector(genelist_DOWNREG_DENV2)

egodown_test <- enrichGO(gene = )

egoDOWN <- enrichGO(gene          = geneDOWN,
                universe      = genelist_DOWNREG_DENV2,
                OrgDb         = org.Mm.eg.db,
                ont           = "ALL",        #BP, CC, or MF
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.05,
                qvalueCutoff  = 0.1,
                readable      = TRUE,
                pool = TRUE)
go_dfDOWN <- as.data.frame(egoDOWN@result)


png(filename="~/Desktop/Downreg_DENV2_barplot.png", width=10, height=10, units="in", res=300)
barplot(egoDOWN, 
        x = "Count",
        color = "p.adjust",
        showCategory = 20)

#go_dfDOWN <- distinct(go_dfDOWN, geneID, .keep_all = TRUE)
go_dfDOWN_20 <- go_dfDOWN[1:20,]

desDOWN <- go_dfDOWN_20$Description
desDOWN <- rev(desDOWN)
go_dfDOWN_20$Description <- factor(go_dfDOWN_20$Description, levels = go_dfDOWN_20$Description[order(-(go_dfDOWN_20$pvalue))])



#GO Figure Lung 
png(filename="~/Desktop/Downreg_DENV2.png", width=500, height=600, units="in", res=300)
ggplot(go_dfDOWN, aes(Description, Count, fill=p.adjust)) + 
  geom_col() +
  coord_flip() +
  scale_x_discrete(labels = str_wrap(des, width = 60)) +
  #scale_fill_viridis() +
  ylab("Number Enriched") +
  xlab("GO Term") +
  theme(
    legend.position = "right",
    text = element_text(size = 10),
    axis.title.x = element_text(size = 10), 
    axis.title.y = element_text(size = 10))

egodownplot <- ggplot(egoDOWN)

```


```{r}


keep <- (rowSums(counts(dds_2)) >= nrow(Metadata_2)) #pre-filter to remove any genes without avg 1 count per sample
dds_2 <- dds_2[keep,]
dds_2 <- estimateSizeFactors(dds_2)
norm_counts_D2 <- as.data.frame(counts(dds_2, normalized=TRUE))
colnames(norm_counts_D2) <- c("Mock1", "DENV2_1", "Mock2","DENV2_2")
write.csv(norm_counts_D2, "~/Desktop/norm_counts_D2.csv")

norm_counts_D2_calcs <- norm_counts_D2 + 1
norm_counts_D2_calcs$treated_vs_untreated_batch1_ratio <- norm_counts_D2_calcs$DENV2_1 / norm_counts_D2_calcs$Mock1
norm_counts_D2_calcs$treated_vs_untreated_batch2_ratio <- norm_counts_D2_calcs$DENV2_2 / norm_counts_D2_calcs$Mock2
norm_counts_D2_calcs$batch1_vs_batch2_ratio <- norm_counts_D2_calcs$treated_vs_untreated_batch1_ratio / norm_counts_D2_calcs$treated_vs_untreated_batch2_ratio
write.csv(norm_counts_D2_calcs, "~/Desktop/D2_counts_and_ratios.csv")

D2_res <- rownames_to_column(norm_counts_D2)
D2_res$l2fc <- log((D2_res$DENV2_1 / D2_res$Mock1), base = 2)

sig_D2_genes <- filter(D2_res, abs(l2fc) > 2, DENV2_1 > 1, Mock1 > 5)

mm <- org.Mm.eg.db
entrez <- AnnotationDbi::select(mm, 
                                keys = D2_res$rowname,
                                columns = c("ENTREZID", "SYMBOL"),
                                keytype = "SYMBOL")
entrez <- distinct(entrez, SYMBOL, .keep_all = TRUE) #removes duplicate entries if there was multiple mapping
D2_res$entrez <- entrez$ENTREZID

write.csv(D2_res, "~/Desktop/D2_results.csv", row.names = FALSE)

D2_res <- filter(D2_res, entrez != "NA") #remove entries where there was not mapping to entrez id. this should mostly affect poorly characterized genes 
D2_res <- filter(D2_res, DENV2_1 > 1, Mock1 > 5)

geneList <- D2_res$l2fc     
names(geneList) = as.character(D2_res$entrez)   
gene <- dplyr::filter(D2_res, abs(l2fc) > 2)

write.csv(gene, "~/Desktop/D2_sig_genes.csv", row.names = FALSE)

gene <- gene$entrez

#GO enrichment
ego <- enrichGO(gene          = gene,
                universe      = names(geneList),
                OrgDb         = org.Mm.eg.db,
                ont           = "ALL",        #BP, CC, or MF
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.05,
                qvalueCutoff  = 0.1,
                readable      = TRUE)
go_df <- as.data.frame(ego@result)
#remove duplicate categories, keeping one with lowest pvalue
go_df <- distinct(go_df, geneID, .keep_all = TRUE)
go_df_20 <- go_df[1:20,]

des <- go_df_20$Description
des <- rev(des)
go_df_20$Description <- factor(go_df_20$Description, levels = go_df_20$Description[order(-(go_df_20$pvalue))])

egoplot <- ggplot(ego)

if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("enrichplot")
library(enrichplot)

#GO Figure Lung 
png(filename="~/Desktop/D2_GO_plot_l2fc2_ALL.png", width=8, height=6, units="in", res=300)
ggplot(go_df_20, aes(Description, Count, fill=p.adjust)) + 
  geom_col() +
  coord_flip() +
  scale_x_discrete(labels = str_wrap(des, width = 60)) +
  #scale_fill_viridis() +
  ylab("Number Enriched") +
  xlab("GO Term") +
  theme(
    legend.position = "right",
    text = element_text(size = 10),
    axis.title.x = element_text(size = 10), 
    axis.title.y = element_text(size = 10))

```

```{r}
#to read the downloaded database from iDEP (from customised input to the webserver)

library(RSQLite)

db <- dbConnect(dbDriver("SQLite"), dbname = "Golden Hamster__mauratus_gene_ensembl.db")
dbListTables(db)

pathwayfromiDEP <- dbReadTable(db, "pathway")
pathwayInfofromiDEP <- dbReadTable(db, "pathwayInfo")

dbDisconnect(db) #to disconnect from db after using it

```



```{r}
D2_res <- rownames_to_column(norm_counts_D2)
D2_res$l2fc_batch2 <- log((D2_res$DENV2_2 / D2_res$Mock2), base = 2)

sig_D2_genes_batch2 <- filter(D2_res, abs(l2fc_batch2) > 2, DENV2_2 > 1, Mock2 > 5)

mm <- org.Mm.eg.db
entrez <- AnnotationDbi::select(mm, 
                                keys = rownames(D2_res),
                                columns = c("ENTREZID", "SYMBOL"),
                                keytype = "SYMBOL")
entrez <- distinct(entrez, SYMBOL, .keep_all = TRUE) #removes duplicate entries if there was multiple mapping
D2_res$entrez <- entrez$ENTREZID

write.csv(D2_res, "~/Desktop/D2_results.csv", row.names = FALSE)

D2_res <- filter(D2_res, entrez != "NA") #remove entries where there was not mapping to entrez id. this should mostly affect poorly characterized genes 
D2_res <- filter(D2_res, DENV2_2 > 1, Mock2 > 5)

geneList2 <- D2_res$l2fc_batch2     
names(geneList2) = as.character(D2_res$entrez2)   
gene2 <- dplyr::filter(D2_res, abs(l2fc_batch2) > 2)

write.csv(gene, "~/Desktop/D2_sig_genes.csv", row.names = FALSE)

gene2 <- gene2$entrez2

#GO enrichment
ego <- enrichGO(gene          = gene2,
                universe      = names(geneList2),
                OrgDb         = org.Mm.eg.db,
                ont           = "MF",        #BP, CC, or MF
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.05,
                qvalueCutoff  = 0.1,
                readable      = TRUE)
go_df <- as.data.frame(ego@result)
#remove duplicate categories, keeping one with lowest pvalue
go_df <- distinct(go_df, geneID, .keep_all = TRUE)
go_df_20 <- go_df[1:20,]

des <- go_df_20$Description
des <- rev(des)
go_df_20$Description <- factor(go_df_20$Description, levels = go_df_20$Description[order(-(go_df_20$pvalue))])

#GO Figure Lung 
png(filename="~/Desktop/D2_GO_plot_l2fc2_ALL_batch2.png", width=8, height=6, units="in", res=300)
ggplot(go_df_20, aes(Description, Count, fill=p.adjust)) + 
  geom_col() +
  coord_flip() +
  scale_x_discrete(labels = str_wrap(des, width = 60)) +
  #scale_fill_viridis() +
  ylab("Number Enriched") +
  xlab("GO Term") +
  theme(
    legend.position = "right",
    text = element_text(size = 10),
    axis.title.x = element_text(size = 10), 
    axis.title.y = element_text(size = 10))
```


```{r}
D2_GA_upreg <- read.csv(("/Users/runchie/Desktop/Ph.D./DEA_runchana/DENV2_GA.csv" 
))

D2_GA_downreg 

problems(D2_GA)
```
View(D2_GA_upreg)
View(D2_GA_downreg)

```{r}
Upreg_ent <- read_excel("/Users/runchie/Desktop/Ph.D./DEA_runchana/Entrez_up.xlsx", sheet = "Sheet 1")

Downreg_ent <- read_excel("/Users/runchie/Desktop/Ph.D./DEA_runchana/Entrez_down.xlsx", sheet = "Sheet 1")



Downreg_D2 <- read_excel("/Users/runchie/Desktop/Ph.D./DEA_runchana/downreg_d2.xlsx", sheet = "Sheet1")

Upreg_D2 <- read_excel("/Users/runchie/Desktop/Ph.D./DEA_runchana/upreg_d2.xlsx", sheet = "Sheet1")
```
```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("org.Mm.eg.db")

library(org.Mm.eg.db)

mm <- org.Mm.eg.db
```

```{r}
D2_down_GA <- as.data.frame(Downreg_D2)
D2_up_GA <- as.data.frame(Upreg_D2)

D2_down_GA$EntrezID <- mapIds(org.Mm.eg.db, keys = rownames(D2_down_GA), keytype = "SYMBOL", column = "ENTREZID")

D2_up_GA$EntrezID <- mapIds(org.Mm.eg.db, keys = rownames(D2_up_GA), keytype = "SYMBOL", column = "ENTREZID")
```

```{r}
entrez_down <- distinct(D2_down_GA, EntrezID, .keep_all = TRUE)
down_res <- filter(entrez_down, EntrezID != "NA")

entrez_up <- distinct(D2_up_GA, EntrezID, .keep_all = TRUE)
up_res <- filter(entrez_up, EntrezID != "NA")

geneListDR <- down_res$l2fc     
names(geneList) = as.character(lung_res$entrez)   
gene <- dplyr::filter(lung_res, abs(l2fc) > 2)
```

```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("pathview")

library(pathview)

pathview(gene.data = rownames(down_res), pathway.id, kegg.dir = ".", cpd.idtype = "kegg", gene.idtype =
"entrez",)
```

```{r}
clusterProfiler()



ggo <- groupGO(gene     = down_res,
               OrgDb    = org.Mm.eg.db,
               ont      = "CC",
               level    = 3,
               readable = TRUE)

head(ggo)
```


```{r}
ggplot(down_res, aes(=))
```


rownames(D2_down_GA)
D2_down_GA <- D2_down_GA %>% remove_rownames %>% column_to_rownames(var="...1")
View(D2_down_GA) 

D2_up_GA <- D2_up_GA %>% remove_rownames %>% column_to_rownames(var="...1")
View(D2_up_GA) 

```{r}
dds2 <- DESeqDataSetFromMatrix(countData = round(coldv2),
                                 colData = Metadata_2,
                                 design= ~ batch + condition)


dds2$condition <- relevel(dds2$condition, ref = "untreated")

dds2 <- DESeq(dds2)
resultsNames(dds2)

res2 <- results(dds2, name="condition_treated_vs_untreated")
view(res2)

resSig2 <- subset(res2, padj < 0.01)
resSig2 # input for ggplot2
summary(resSig2)


write.csv( as.data.frame(resSig2), file = "resultsig_denv2.1.csv")


df2=as.data.frame(resSig2)
df2$diffexpressed <- "NO"
head(df2)
df2$delabel <- NA

df2$diffexpressed[df2$log2FoldChange>1 & df2$pvalue<0.01] <- "Upregulated"
df2$diffexpressed[df2$log2FoldChange<1 & df2$pvalue<0.01] <- "Downregulated"
df2$diffexpressed[df2$log2FoldChange>-1 & df2$log2FoldChange<1] <- "Non-significant"


plot2 <- ggplot(data=df2,aes(x=log2FoldChange, y=-log10(pvalue), col=diffexpressed, label=delabel)) + geom_point(shape = 21) + theme_minimal() + geom_text() + geom_text_repel() + scale_color_manual(values =c('blue','grey','red')) + theme(text=element_text(size=20)) + geom_vline(xintercept=c(-1, 1),linetype = "dashed", col='grey') + geom_hline(yintercept=-log(0.001),linetype = "dashed", col='grey') + ggtitle("DENV-4")
```
```{r}
#Pathway Analysis
#restricting search space to genes with > 5 counts in uninfected (to match heatmap), > abs(2) l2fc (ie > 4 fold change)
#Create results by calculating l2fc of infected_untreated / uninfected

lung_res <- rownames_to_column(norm_counts_lung)
lung_res$l2fc <- log((lung_res$infected_untreated / lung_res$uninfected), base = 2)

sig_lung_genes <- filter(lung_res, abs(l2fc) > 2, infected_untreated > 1, uninfected > 5)

mm <- org.Mm.eg.db
entrez <- AnnotationDbi::select(mm, 
                                keys = lung_res$rowname,
                                columns = c("ENTREZID", "SYMBOL"),
                                keytype = "SYMBOL")
entrez <- distinct(entrez, SYMBOL, .keep_all = TRUE) #removes duplicate entries if there was multiple mapping
lung_res$entrez <- entrez$ENTREZID

write.csv(lung_res, "~/Desktop/lung_results.csv", row.names = FALSE)

lung_res <- filter(lung_res, entrez != "NA") #remove entries where there was not mapping to entrez id. this should mostly affect poorly characterized genes 
lung_res <- filter(lung_res, infected_untreated > 1, uninfected > 5)


geneList <- lung_res$l2fc     
names(geneList) = as.character(lung_res$entrez)   
gene <- dplyr::filter(lung_res, abs(l2fc) > 2)

write.csv(gene, "~/Desktop/lung_sig_genes.csv", row.names = FALSE)

gene <- gene$entrez
```


```{r}


#GO enrichment
ego <- enrichGO(gene          = gene,
                universe      = names(geneList),
                OrgDb         = org.Mm.eg.db,
                ont           = "BP",        #BP, CC, or MF
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.05,
                qvalueCutoff  = 0.1,
                readable      = TRUE)
go_df <- as.data.frame(ego@result)
#remove duplicate categories, keeping one with lowest pvalue
go_df <- distinct(go_df, geneID, .keep_all = TRUE)
go_df_20 <- go_df[1:20,]

des <- go_df_20$Description
des <- rev(des)
go_df_20$Description <- factor(go_df_20$Description, levels = go_df_20$Description[order(-(go_df_20$pvalue))])


```

```{r}
#GO Figure Lung 
png(filename="~/Desktop/lung_GO_plot_l2fc2_BP.png", width=8, height=6, units="in", res=300)
ggplot(go_df_20, aes(Description, Count, fill=p.adjust)) + 
  geom_col() +
  coord_flip() +
  scale_x_discrete(labels = str_wrap(des, width = 60)) +
  scale_fill_viridis() +
  ylab("Number Enriched") +
  xlab("GO Term") +
  theme(
    legend.position = "right",
    text = element_text(size = 10),
    axis.title.x = element_text(size = 10), 
    axis.title.y = element_text(size = 10))
dev.off()
```

